### ISSUE TITLE
"Maximum call stack size exceeded" error when fetching data from Binance

### ISSUE THREAD

**Issue by anvd** [Superalgos/Superalgos#313]
## Context

**Operating System:** MacOs runs Chrome, Ubuntu 20.04 runs backend.

**Software version:** develop branch, commit f24796c32

**Workspace version:** "Plugin -> Trading-System-Design-Tutorials".

**Reproducible:** the issue may not be reproduced.

### 1. Explain what the problem seems to be.

Click "Run All Projects Data Tasks" to fetch candles-volumes data from Binance. There is an exception in the middle of the process with message "Maximum call stack size exceeded". 
<img width="1436" alt="Screen Shot 2021-01-01 at 1 36 03 PM" src="https://user-images.githubusercontent.com/12640348/103434698-96b09800-4c37-11eb-8d78-1120e91f5296.png">

### 2. Clearly explain what you wish to accomplish.
The process should be complete with the above exception.

**Comment by anvd** [comment]
Same issue when fetching data for ETH/USDT market from Binance
<img width="1436" alt="Screen Shot 2021-01-01 at 1 36 03 PM" src="https://user-images.githubusercontent.com/12640348/104089234-cbf46000-529f-11eb-8c1d-46d7919d5e17.png">

**Comment by yemartin** [comment]
Same issue on `master`, commit 12fc48bcc2b2dadcb33e9632241d67d6f2405edd, doing the "Getting started" tutorial, in the "Let's Mine Some Data!" step.

This seems reproducible as of now: I erased `Data-Storage`, `Log-Files` and `My-Workspaces` to get back a clean checkout state, and restarted the tutorial from the beginning. The same error happened:

```
2021-01-12T21:42:05.219Z              Binance   BTC/USDT              Masters              Exchange-Raw-Data                Historic-OHLCVs          Main Loop #        2
2021-01-12T21:42:05.236Z              Binance   BTC/USDT              Masters                Candles-Volumes             Multi-Period-Daily      Internal Loop #        1                     2020-02-25    14.81 %
2021-01-12T21:42:05.244Z              Binance   BTC/USDT              Masters                Candles-Volumes            Multi-Period-Market      Internal Loop #        1                     2020-03-17    20.37 %
2021-01-12T21:42:05.926Z              Binance   BTC/USDT              Masters                Candles-Volumes            Multi-Period-Market      Internal Loop #        1                     2020-03-18    20.63 %
2021-01-12T21:42:06.273Z              Binance   BTC/USDT              Masters                Candles-Volumes             Multi-Period-Daily      Internal Loop #        1                     2020-02-26    15.08 %
2021-01-12T21:42:06.635Z              Binance   BTC/USDT              Masters                Candles-Volumes            Multi-Period-Market      Internal Loop #        1                     2020-03-19    20.90 %
[ERROR] Task Server -> Node JS Process -> uncaughtException -> err.message = Maximum call stack size exceeded
[ERROR] Task Server -> Node JS Process -> uncaughtException -> err.stack = RangeError: Maximum call stack size exceeded
    at Math.trunc (<anonymous>)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:489:52)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
RangeError: Maximum call stack size exceeded
    at Math.trunc (<anonymous>)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:489:52)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
    at checkOHLCVMinute (/srv/Superalgos/app/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js:508:37)
2021-01-12T21:42:07.155Z              Binance   BTC/USDT              Masters                Candles-Volumes             Multi-Period-Daily      Internal Loop #        1                     2020-02-27    15.34 %
2021-01-12T21:42:07.345Z              Binance   BTC/USDT              Masters                Candles-Volumes            Multi-Period-Market      Internal Loop #        1                     2020-03-20    21.16 %
2021-01-12T21:42:08.069Z              Binance   BTC/USDT              Masters                Candles-Volumes             Multi-Period-Daily      Internal Loop #        1                     2020-02-28    15.61 %
2021-01-12T21:42:08.103Z              Binance   BTC/USDT              Masters                Candles-Volumes            Multi-Period-Market      Internal Loop #        1                     2020-03-21    21.43 %
2021-01-12T21:42:08.900Z              Binance   BTC/USDT              Masters                Candles-Volumes            Multi-Period-Market      Internal Loop #        1                     2020-03-22    21.69 %
```

**Comment by Luis-Fernando-Molina** [comment]
This was fixed.

**Comment by yemartin** [comment]
Hi @Luis-Fernando-Molina! Can you clarify what commit fixed it? I just pulled `master` (now on commit b2ea6d4), but it is still happening (note: for me it is consistently happening  at 0:00 UTC).

**Comment by Luis-Fernando-Molina** [comment]
> Hi @Luis-Fernando-Molina! Can you clarify what commit fixed it? I just pulled master (now on commit b2ea6d4), but it is still happening (note: for me it is consistently happening at 0:00 UTC)

yes, sure,  the fix is at the develop branch. Just get the latest that also have other bug fixes.
